---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "my-subpath"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
